---
# # # # # # # # # #
#  K i k o f r i  #
# # # # # # # # # #

# Basic
name: "Rakesh Malviya"
description: "Blog on Machine learning and more ..."

# URL
url: " "
#baseurl: ""
permalink: /:year/:month/:day/:title.html

# Markdown
markdown: kramdown

# Navigation
nav:
 - name: "about"
   href: "https://sites.google.com/site/rakeshmalviyasite/"

 - name: "reference"
   href: "https://sites.google.com/site/rakeshmalviyasite/"

 - name: "contact"
   href: "http://www.google.com/recaptcha/mailhide/d?k=017_0qSck4Ft9xRcnngcfzJQ==&c=sEsD2TK-tMZCx9Z_bRcR0UPr_KY1y-iOlnZr-W3bLZ0=" 

tag_page: '/tags'
# Sass
sass:
 style: :compressed

# Excerpt
excerpt_separator: <!-ex->


#Gems
plugins: [jekyll-paginate,jekyll-seo-tag]
paginate: 10
paginate_path: "/page:num/"

# Scopes
defaults:
 -
  scope:
   path: ""
   type: "pages"
  values:
   layout: "page"
 -
  scope:
   path: ""
   type: "posts"
  values:
   layout: "post"

 - 
  scope:
   path: "assets/img"
  values:
   image: true

---
